drop table SandboxPrescription 
drop table SandboxPrescriptionItem 
create table SandboxPrescription (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Date DATE,
	Patient VARCHAR(MAX),
	Diagnosis VARCHAR(MAX)
);
set identity_insert sandboxprescription on
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (1, '01/13/2018', 'Odo Witherden', 'Obstetric shock-deliver');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (2, '12/25/2017', 'Tiff Cockland', 'Chr gc upper gu NEC');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (3, '04/16/2018', 'Lek Iianon', 'Outlet contract-antepart');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (4, '12/13/2017', 'Angel Elphick', 'Poisoning-antidotes NEC');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (5, '03/13/2018', 'Bettine Daud', '3rd deg burn thumb');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (6, '12/03/2017', 'Rosabel Well', 'Lacrimal syst dis NEC');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (7, '07/31/2017', 'Anton Gentric', 'Ben neo soft tissue NEC');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (8, '10/25/2017', 'Cass Braben', 'Cl skul base fx-coma NOS');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (9, '01/17/2018', 'Ann Simonazzi', 'Osteomyelitis NOS-mult');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (10, '04/29/2018', 'Reuben Lempel', 'Tubrcloma brain-micro dx');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (11, '04/03/2018', 'Arel Edmondson', 'Dental caries - enamel');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (12, '12/02/2017', 'Bobbi Scanlin', 'War inj:hnd-hnd combat');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (13, '05/30/2017', 'Adolphus Haug', 'Legionnaires'' disease');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (14, '05/13/2018', 'Collin Poel', 'Terrorism, biologicals');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (15, '09/29/2017', 'Harv Cready', 'Hypotropia');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (16, '11/27/2017', 'Cicily Westcott', 'Immersion foot');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (17, '02/26/2018', 'Nealson Falkinder', 'Vitreous prolapse');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (18, '01/09/2018', 'Gale Ricardo', 'Neuropathy in malig dis');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (19, '09/01/2017', 'Tallie Manueli', 'Macular cyst or hole');
insert into SandboxPrescription (Id, Date, Patient, Diagnosis) values (20, '09/04/2017', 'Jobie Thaim', '3rd deg burn knee');
set identity_insert sandboxprescription off
create table SandboxPrescriptionItem (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	SandboxPrescriptionId INT,
	Item VARCHAR(MAX),
	IsAvailable BIT
);
set identity_insert sandboxprescriptionitem on
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (1, 3, 'Lorcet Plus', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (2, 14, 'Hydrocortisone', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (3, 5, 'Personal Care Petroleum', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (4, 7, 'Multi symptom Nighttime', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (5, 6, 'Extra Strength Aspirin Free Pain Relief', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (6, 11, 'IASO PROGRESSIVE AGE CARE', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (7, 11, 'DOUBLE WEAR LIGHT', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (8, 8, 'LEVOXYL', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (9, 5, 'Olay Age Defying Mature Skin', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (10, 6, 'Degree Nature Effects Orange Flower and Cranberry', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (11, 12, 'Ropinirole', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (12, 2, 'HEMETAB', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (13, 9, 'Motion Medicine', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (14, 1, 'germstarNORO', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (15, 8, 'Pain Relieving Patch', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (16, 6, 'SHISEIDO ADVANCED HYDRO-LIQUID COMPACT (REFILL)', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (17, 17, 'LEVOTHYROXINE SODIUM', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (18, 17, 'esika', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (19, 3, 'Severe Sinus Congestion and Pain Daytime', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (20, 19, 'Lisinopril and Hydrochlorothiazide', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (21, 5, 'pain relief', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (22, 20, 'Childrens Acetaminophen', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (23, 17, 'AK-Con', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (24, 17, 'BETULA LENTA POLLEN', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (25, 9, 'Formica Arnica', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (26, 3, 'Xylocaine', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (27, 8, 'BPO Creamy Wash Complete Pack', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (28, 16, 'Nicotine Polacrilex', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (29, 2, 'Childrens Pain and Fever', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (30, 9, 'AVANDIA', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (31, 4, 'Rizatriptan Benzoate', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (32, 20, 'BZK Pads', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (33, 3, 'ELF TINTED MOISTURIZER', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (34, 13, '24 HOUR', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (35, 18, 'Gemcitabine', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (36, 14, 'GODDESS GARDEN ORGANICS Sunny Face NATURAL SUNSCREEN BROAD SPECTRUM SPF 30 WATER RESISTANT', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (37, 17, 'Alodox', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (38, 15, 'Atomoxetine Hydrochloride', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (39, 7, 'BareMinerals', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (40, 9, 'Purell Instant Ultra', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (41, 4, 'Ginger', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (42, 9, 'BIOSOLIS Face UVA Sunscreen Broad Spectrum SPF30', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (43, 14, 'Simvastatin', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (44, 9, 'Humalog', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (45, 15, 'Honeydew Melon', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (46, 13, 'IBUPROFEN', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (47, 18, 'Amlodipine Besylate', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (48, 18, 'Ongo - Fin', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (49, 2, 'Therabenzaprine-90-5', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (50, 19, 'Cultivated Oat', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (51, 13, 'Red Mulberry', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (52, 15, 'Metoprolol Tartrate', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (53, 13, 'Zonisamide', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (54, 19, 'Arizona Ash', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (55, 11, 'Nivea For Men Protective', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (56, 7, 'Amoxicillin', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (57, 13, 'Regular Strength Aspirin', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (58, 16, 'Metolazone', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (59, 17, 'Plavix', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (60, 2, 'Chlordiazepoxide and Amitriptyline Hydrochloride', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (61, 15, 'Fenoldopam Mesylate', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (62, 2, 'Depakene', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (63, 11, 'Epinephrine', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (64, 13, 'SHISEIDO SHEER MATIFYING COMPACT (REFILL)', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (65, 11, 'Promethazine Hydrochloride', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (66, 12, 'Dr G Whitening REFORMER by EGF', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (67, 10, 'LBEL', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (68, 20, 'SUPER ORIGIN COLLAGEN BB', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (69, 11, 'Miracle Foot Repair', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (70, 18, 'CobraZol', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (71, 1, 'Pac-Kit Motion Sickness', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (72, 3, 'FOSAMAX PLUS D', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (73, 12, 'Carisoprodol', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (74, 6, 'Lotensin HCT', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (75, 6, 'Baclofen', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (76, 17, 'Alora', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (77, 20, 'benzonatate', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (78, 5, 'Hydroxychloroquine Sulfate', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (79, 7, 'Losartan Potassium', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (80, 2, 'Dolce and Gabbana The Primer Sheer Radiance', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (81, 5, 'Clearskin', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (82, 6, 'Methenamine Hippurate', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (83, 7, 'Vegetability Natural', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (84, 12, 'Diazepam', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (85, 7, 'ibuprofen', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (86, 20, 'Easy Care First Aid Chest - Home and Workshop', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (87, 20, 'Systane', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (88, 9, 'CC Cream Medium', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (89, 10, 'Aceon', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (90, 6, 'Extra Strength Pain Relief', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (91, 10, 'Feelin Fresh Original', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (92, 5, 'Acid Reducer', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (93, 1, 'Simvastatin', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (94, 1, 'Levofloxacin', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (95, 19, 'Penicillium Mixture', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (96, 5, 'Australian Gold', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (97, 12, 'LBEL', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (98, 19, 'Medline Alcohol Swabstick', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (99, 13, 'AZITHROMYCIN', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (100, 7, 'TOPIRAMATE', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (101, 7, 'Carelessweed', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (102, 16, 'Sertraline Hydrochloride', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (103, 6, 'Formica Arnica', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (104, 20, 'XtraCare Invisible Solid Lady Stick Powder Fresh', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (105, 19, 'PERFECTION LUMIERE VELVET', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (106, 6, 'rx act anti diarrheal', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (107, 3, 'Chlorhexidine Gluconate', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (108, 6, 'Actoplus Met', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (109, 10, 'SuperPlus Beblesh Balm Triple Functions SPF25 PA 2Plus', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (110, 11, 'Cefepime Hydrochloride', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (111, 11, 'Bonine', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (112, 3, 'milk of magnesia', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (113, 13, 'Ziprasidone Hydrochloride', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (114, 2, 'DOCUSATE SODIUM', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (115, 18, 'Cough', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (116, 11, 'Hand Sanitizer with Moisturizers', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (117, 8, 'HYDROMORPHONE HYDROCHLORIDE', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (118, 16, 'Antibactierial Hand Sanitizer', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (119, 13, 'ck one waterfresh face makeup spf 15', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (120, 4, 'Acetaminophen, Diphenhydramine Hydrochloride, Phenylephrine Hydrochloride', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (121, 8, 'Old Spice Fresher Collection Citron', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (122, 12, 'Naratriptan Hydrochloride', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (123, 2, 'ORPHENADRINE CITRATE', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (124, 9, 'Albuterol Sulfate', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (125, 1, 'Risperidone', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (126, 15, 'Ultimate Rescue', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (127, 3, 'Allergy Relief', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (128, 11, 'QUALITY CHOICE ORIGINAL EYE DROPS', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (129, 11, 'Metolazone', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (130, 18, 'Mirtazapine', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (131, 19, 'Handi-San', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (132, 1, 'Nighttime Sleep Aid', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (133, 6, 'healthy accents omeprazole', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (134, 8, 'Goodys', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (135, 3, 'Alcohol Swabs with Benzocaine', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (136, 19, 'Nasacort Allergy 24HR', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (137, 18, 'Metoprolol Tartrate', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (138, 1, 'Acyclovir', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (139, 9, 'Fluconazole', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (140, 4, 'Instant Hand Sanitizing Wipes', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (141, 19, 'COTTON LINTERS', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (142, 20, 'Quality Petroleum Aloe Vera', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (143, 4, 'IDkit HP ONE', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (144, 16, 'U-max Whitening Functional Essence', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (145, 8, 'Vitamin A D', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (146, 5, 'CIPROFLOXACIN', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (147, 13, 'Oxygen', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (148, 1, 'Skin Rashes Eczema', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (149, 3, 'Aspirin', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (150, 7, 'FLEBEAUTE COLLAGENIC SKIN COVER', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (151, 7, 'Equate Ibuprofen', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (152, 3, 'Holiday EleganceFrosted GingerbreFrosted Gingerbre', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (153, 15, 'Pleo Ut', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (154, 11, 'Healthy Accents cold head congestion', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (155, 11, 'Sulfamethoxazole and Trimethoprim', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (156, 19, 'Citalopram', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (157, 9, 'CLINIMIX', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (158, 15, 'Nitrolingual', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (159, 3, 'Dicyclomine', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (160, 7, 'Red (River) Birch', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (161, 9, 'Primidone', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (162, 5, 'Clindamycin Hydrochloride', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (163, 4, 'Cephalexin', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (164, 17, 'Ibuprofen', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (165, 6, 'Adidas 24H Anti Perspirant', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (166, 9, 'CLADOSPORIUM SPHAEROSPERMUM', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (167, 13, 'cold and cough nighttime', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (168, 5, 'Cotton Linters', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (169, 6, 'Dexferrum', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (170, 2, 'Cholestop', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (171, 16, 'Cold and Hot', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (172, 18, 'SH18 Skin Lightening', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (173, 13, 'Amlodipine Besylate', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (174, 1, 'Ibuprofen', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (175, 2, 'Metoclopramide', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (176, 11, 'Cucumber', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (177, 13, 'up and up cold relief', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (178, 3, 'CounterAct', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (179, 2, 'Meijer Cherry Cough Drops', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (180, 15, 'Rhodotorula mucilaginosa', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (181, 19, 'Minoxidil', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (182, 7, 'Coppertone ultraGUARD Sunscreen', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (183, 8, 'Bacitracin', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (184, 13, 'VENLAFAXINE HYDROCHLORIDE', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (185, 15, 'Dextrose', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (186, 13, 'Orphenadrine Citrate', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (187, 20, 'Lovastatin', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (188, 3, 'Dilacor', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (189, 16, 'Meclizine HCl', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (190, 1, 'Menstrual Relief', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (191, 2, 'Furosemide', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (192, 9, 'Triple-Vitamin Drops with Fluoride', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (193, 5, 'Dexamethasone Intensol', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (194, 15, 'leader aspirin', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (195, 7, 'SoftCIDE-ES', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (196, 20, 'Midazolam Hydrochloride', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (197, 2, 'RANITIDINE', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (198, 4, 'Divalproex sodium', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (199, 4, 'Argatroban', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (200, 6, 'flormar Soft Touch Foundation Sunscreen Broad Spectrum SPF 20 ST08 Bronze Beige', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (201, 12, 'SuperSmile Professional', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (202, 4, 'Good Neighbor Pharmacy Nasal Decongestant', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (203, 4, 'Benztropine Mesylate', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (204, 1, 'SKIN ERUPTIONS', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (205, 15, 'Lisinopril', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (206, 10, 'Timolol Maleate', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (207, 8, 'VASOPRESSIN', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (208, 15, 'Lisinopril and Hydrochlorothiazide', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (209, 6, 'mupirocin', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (210, 9, 'DICYCLOMINE HYDROCHLORIDE', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (211, 19, 'Cabbage', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (212, 9, 'Freshmist Sensitive Toothpaste', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (213, 17, 'care one lice killing', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (214, 7, 'Olanzapine', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (215, 2, 'Benazepril Hydrochloride', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (216, 15, 'stila CC color correcting broad-spectrum SPF 20 05 RICH MEDIUM', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (217, 2, 'dg health infants pain and fever', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (218, 11, 'Retin-A', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (219, 6, 'CLE DE PEAU BEAUTE RADIANT FLUID FOUNDATION', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (220, 7, 'REMEDY Calazime Skin Protectant', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (221, 17, 'PDI Sani-Hands ALC', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (222, 8, 'Levofloxacin', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (223, 13, 'Solar Sense Zany Zinc SPF 50 - Pink', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (224, 16, 'HCG Plus', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (225, 14, 'Phenobarbital', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (226, 2, 'JETREA', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (227, 17, 'Olanzapine', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (228, 16, 'Sertraline Hydrochloride', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (229, 1, 'Diazepam', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (230, 20, 'Loratadine', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (231, 10, 'CITALOPRAM', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (232, 5, 'Midazolam Hydrochloride', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (233, 12, 'Amlodipine besylate and benazepril hydrochloride', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (234, 5, 'Neutrogena Sensitive Skin', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (235, 11, 'Lorazepam', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (236, 10, 'Flower O Life', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (237, 20, 'Bain de Soleil', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (238, 16, 'White Potato', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (239, 6, 'SHISEIDO BENEFIANCE WRINKLERESIST24 DAY', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (240, 8, 'Meijer', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (241, 6, 'Meperidine Hydrochloride', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (242, 10, 'Strattera', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (243, 3, 'Rocky Mountain Sunscreen', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (244, 4, 'Warfarin Sodium', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (245, 14, 'Flurazepam', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (246, 13, 'Valacyclovir Hydrochloride', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (247, 11, 'Thiothixene', 0);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (248, 10, 'CLE DE PEAU BEAUTE SILKY FOUNDATION I', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (249, 10, 'Scott-Vincent Borba', 1);
insert into SandboxPrescriptionItem (Id, SandboxPrescriptionId, Item, IsAvailable) values (250, 6, 'Amiloride Hydrochloride and Hydrochlorothiazide', 1);
set identity_insert sandboxprescriptionitem off